# Generated by Django 5.1.7 on 2025-04-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=200)),
                ('flight_name', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('departutre_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_seats', models.IntegerField()),
                ('flight_type', models.CharField(max_length=200)),
                ('food_supply', models.BooleanField(default=True)),
            ],
        ),
    ]
