# Generated by Django 5.1.7 on 2025-04-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='food_supply',
            field=models.BooleanField(default=False),
        ),
    ]
