# Generated by Django 5.1.7 on 2025-04-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customeapp', '0002_alter_flight_food_supply'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flight',
            new_name='FLIGHTS',
        ),
    ]
